# Generated by Django 3.1 on 2020-08-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatru', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traduccion',
            new_name='Translation',
        ),
    ]
